### ISSUE TITLE
I want to run ME2.0 fmu file, but i don't know how to get completed value !

### ISSUE THREAD

**Issue by the-doo** [NTNU-IHB/FMI4j#141]
This project is awesome and greate!!!

I has some question when I used.

Where can I find an example？

Has any like CoSimulationSlave.doStep method in ModelExchangeInstance?

Thanks!!!

**Comment by markaren** [comment]
FMI4cpp simply _enables_ you to use FMI 2.0 for ME, but does not in any way, shape or form build on that. I.e., in order to use ME models sucessfully you need to provide a solver and use the API correctly in order to simulate the model. I, myself cannot help with that. You could take a look at [FMPy](https://github.com/CATIA-Systems/FMPy), which allows you to simulate ME models (not just access the FMI API).

**Comment by the-doo** [comment]
Maybe that‘s my question, what's the correctly API?

**Comment by markaren** [comment]
The very best I can do is point you to: https://github.com/NTNU-IHB/FMI4j/pull/96/files 
This approach was taken from FMPy. But it is no longer in the scope of FMU4j to provide this feature. You will need to figure this out on your own. I recommend studying the FMPy sources.  

Perhaps ME is not really what you want to use? There should be some tools online that would be able to convert an ME FMU into a CS one.

Closing as the question is out scope for this project.
